<?php

/*
 * This file is part of the Symfony package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Symfony\Component\Config\Definition\Configurator;

return static function (DefinitionConfigurator $configurator): void {
    $configurator->rootNode()
        ->children()
            ->scalarNode('app')->defaultValue('app')->end()
            ->scalarNode('version')->defaultValue('0.0.1')->end()
            ->scalarNode('description')->defaultNull()->end()
            ->arrayNode('icons')
                ->arrayPrototype()
                    ->children()
                        ->scalarNode('src')->isRequired()->end()
                        ->scalarNode('mime_type')->defaultNull()->end()
                        ->arrayNode('sizes')
                            ->scalarPrototype()->end()
                            ->defaultValue(['any'])
                        ->end()
                    ->end()
                ->end()
            ->end()
            ->scalarNode('website_url')->defaultNull()->end()
            ->integerNode('pagination_limit')->defaultValue(50)->end()
            ->scalarNode('instructions')->defaultNull()->end()
            ->arrayNode('client_transports')
                ->children()
                    ->booleanNode('stdio')->defaultFalse()->end()
                    ->booleanNode('http')->defaultFalse()->end()
                ->end()
            ->end()
            ->arrayNode('discovery')
                ->addDefaultsIfNotSet()
                ->children()
                    ->arrayNode('scan_dirs')
                        ->scalarPrototype()->end()
                        ->defaultValue(['src'])
                    ->end()
                    ->arrayNode('exclude_dirs')
                        ->scalarPrototype()->end()
                        ->defaultValue([])
                    ->end()
                ->end()
            ->end()
            ->arrayNode('http')
                ->addDefaultsIfNotSet()
                ->children()
                    ->scalarNode('path')->defaultValue('/_mcp')->end()
                    ->arrayNode('session')
                        ->addDefaultsIfNotSet()
                        ->children()
                            ->enumNode('store')->values(['file', 'memory', 'cache', 'framework'])->defaultValue('file')->end()
                            ->scalarNode('directory')->defaultValue('%kernel.cache_dir%/mcp-sessions')->end()
                            ->scalarNode('cache_pool')->defaultValue('cache.mcp.sessions')->end()
                            ->scalarNode('prefix')->defaultValue('mcp-')->end()
                            ->integerNode('ttl')->min(1)->defaultValue(3600)->end()
                        ->end()
                    ->end()
                ->end()
            ->end()
            ->arrayNode('oauth')
                ->canBeEnabled()
                ->info('Turn the MCP server into its own OAuth 2.1 authorization server, backed by league/oauth2-server-bundle.')
                ->children()
                    ->scalarNode('issuer')->defaultNull()->info('Public base URL of the authorization server (issuer). Required when enabled.')->end()
                    ->scalarNode('resource')->defaultNull()->info('Protected resource identifier (RFC 8707). Defaults to issuer + MCP http path.')->end()
                    ->arrayNode('scopes')
                        ->scalarPrototype()->end()
                        ->defaultValue(['mcp:tools', 'mcp:resources'])
                    ->end()
                    ->integerNode('access_token_ttl')->defaultValue(3600)->info('Access token lifetime in seconds.')->end()
                    ->integerNode('refresh_token_ttl')->defaultValue(1209600)->info('Refresh token lifetime in seconds.')->end()
                    ->integerNode('authorization_code_ttl')->defaultValue(600)->info('Authorization code lifetime in seconds.')->end()
                    ->scalarNode('encryption_key')->defaultNull()->info('Encryption key for league token payloads (plain string or defuse key). Required when enabled.')->end()
                    ->scalarNode('login_path')->defaultValue('/login')->info('Where unauthenticated users are redirected during authorization.')->end()
                    ->scalarNode('consent')->defaultNull()->info('Service id deciding whether consent is required. Defaults to auto-approve.')->end()
                    ->booleanNode('client_registration')->defaultTrue()->info('Enable RFC 7591 dynamic client registration.')->end()
                    ->arrayNode('signing_key')
                        ->addDefaultsIfNotSet()
                        ->children()
                            ->scalarNode('private_key')->defaultNull()->info('Path to the PEM-encoded RSA private key. Required when enabled.')->end()
                            ->scalarNode('public_key')->defaultNull()->info('Path to the PEM-encoded RSA public key. Required when enabled.')->end()
                            ->scalarNode('passphrase')->defaultNull()->end()
                            ->scalarNode('key_id')->defaultNull()->info('Key id advertised in the JWKS document. Derived from the public key when omitted.')->end()
                        ->end()
                    ->end()
                    ->arrayNode('persistence')
                        ->addDefaultsIfNotSet()
                        ->info('How league/oauth2-server-bundle persists clients, codes and tokens.')
                        ->children()
                            ->enumNode('type')->values(['in_memory', 'doctrine'])->defaultValue('in_memory')->end()
                            ->scalarNode('entity_manager')->defaultValue('default')->info('Doctrine entity manager (persistence.type=doctrine).')->end()
                            ->scalarNode('table_prefix')->defaultValue('oauth2_')->info('Table prefix (persistence.type=doctrine).')->end()
                        ->end()
                    ->end()
                    ->arrayNode('endpoints')
                        ->addDefaultsIfNotSet()
                        ->children()
                            ->scalarNode('authorize')->defaultValue('/oauth/authorize')->end()
                            ->scalarNode('token')->defaultValue('/oauth/token')->end()
                            ->scalarNode('register')->defaultValue('/oauth/register')->end()
                        ->end()
                    ->end()
                ->end()
            ->end()
        ->end()
    ;
};
